### ISSUE TITLE
The agent should store its systemid in a more permanent location

### ISSUE THREAD

**Issue by guidow** [pyfarm/pyfarm-agent#170]
The agent stores its systemid in a temp directory by default. If the temp directory gets deleted at some point, it will lose that systemid and create a new one at the next restart, which can lead to a duplicated entry on the master.

On most linux systems, /tmp gets emptied on every reboot by default. Windows doesn't automatically delete temp directories by default to my knowledge, but many users and system administrators do it anyway.

The agent needs to use a better, more permanent location for it systemid.

**Comment by opalmer** [comment]
Closing this....systemids are no longer a thing.
